[env]
LUAROCKS_VERSION = "3.11.1"
ASDF_LUA_LUAROCKS_VERSION = "3.11.1"
RUBY_CONFIGURE_OPTS = "--enable-zjit"

[tools]
elixir = "1.18.2"
elixir-ls = "0.30.0"
erlang = "27.3.3"
lua-language-server = "3.15.0"
neovim = "0.11.5"
nodejs = "24.11.1"
postgres = "18.1"
ruby = "3.4.8"
rust = "1.89.0"
shellcheck = "0.11.0"
shfmt = "3.12.0"
stylua = "2.1.0"
usage = "latest"
yarn = "4.12.0"
